import { Gram } from "@gram-ai/functions";
import { z } from "zod";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";

const DEFAULT_MCP_URL = "https://planetscale.com/docs/mcp";

/**
 * The upstream docs MCP server is generated by Mintlify, which owns the tool
 * name and its schema. Mintlify renamed this tool from `SearchPlanetScale` to
 * snake_case in early 2026 and narrowed the schema to `query` alone, so the
 * name below is a moving target rather than a constant we control. The current
 * list is published, unauthenticated, at
 * `https://planetscale.com/docs/.well-known/mcp/server-card.json`.
 */
const UPSTREAM_TOOL_NAME = "search_planet_scale";

/** Longest `snippet` kept per result; upstream blocks run to ~10KB each. */
const SNIPPET_MAX_LENGTH = 1500;

type NormalizedResult = {
  title?: string;
  url?: string;
  page?: string;
  snippet?: string;
  truncated?: boolean;
  text?: string;
  metadata?: Record<string, unknown>;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function pickFirstString(...values: unknown[]): string | undefined {
  for (const value of values) {
    if (typeof value === "string" && value.trim().length > 0) {
      return value;
    }
  }
  return undefined;
}

function truncateSnippet(content: string): {
  snippet: string;
  truncated: boolean;
} {
  const trimmed = content.trim();
  if (trimmed.length <= SNIPPET_MAX_LENGTH) {
    return { snippet: trimmed, truncated: false };
  }
  return { snippet: `${trimmed.slice(0, SNIPPET_MAX_LENGTH)}…`, truncated: true };
}

/**
 * Parse one upstream text block. Each block is a single search hit shaped as
 * `Title:`/`Link:`/`Page:` header lines followed by a `Content:` body that runs
 * to the end of the block:
 *
 *     Title: Available query statistics
 *     Link: https://planetscale.com/docs/vitess/monitoring/query-insights#...
 *     Page: vitess/monitoring/query-insights
 *     Content: ### Available query statistics
 *
 *     You can customize the metrics ...
 *
 * Only lines ahead of `Content:` are read as headers, so a `Summary:` line
 * inside an API reference body stays part of the content. Returns `undefined`
 * when the block carries none of these headers, which lets the caller fall
 * back to keeping the raw text rather than dropping the hit.
 */
export function parseDocsTextBlock(text: string): NormalizedResult | undefined {
  const headers = new Map<string, string>();
  const lines = text.split("\n");

  let contentStart = -1;
  for (const [index, line] of lines.entries()) {
    const match = /^(Title|Link|Page|Content): ?(.*)$/.exec(line);
    if (!match) {
      continue;
    }

    const [, key, value] = match;
    if (key === "Content") {
      headers.set(key, value ?? "");
      contentStart = index;
      break;
    }

    headers.set(key!, value ?? "");
  }

  if (headers.size === 0) {
    return undefined;
  }

  const body =
    contentStart === -1
      ? undefined
      : [headers.get("Content") ?? "", ...lines.slice(contentStart + 1)].join("\n");

  const result: NormalizedResult = {
    title: pickFirstString(headers.get("Title")),
    url: pickFirstString(headers.get("Link")),
    page: pickFirstString(headers.get("Page")),
  };

  if (body !== undefined && body.trim().length > 0) {
    const { snippet, truncated } = truncateSnippet(body);
    result.snippet = snippet;
    if (truncated) {
      result.truncated = true;
    }
  }

  return result;
}

function normalizeEntry(entry: unknown): NormalizedResult {
  if (typeof entry === "string") {
    return { text: entry };
  }

  if (!isRecord(entry)) {
    return {};
  }

  const title = pickFirstString(
    entry["title"],
    entry["name"],
    entry["heading"],
    entry["page_title"]
  );
  const url = pickFirstString(
    entry["url"],
    entry["href"],
    entry["link"],
    entry["uri"]
  );
  const snippet = pickFirstString(
    entry["snippet"],
    entry["summary"],
    entry["excerpt"],
    entry["content"],
    entry["text"]
  );

  const metadata: Record<string, unknown> = { ...entry };
  for (const key of ["title", "name", "heading", "page_title", "url", "href", "link", "uri", "snippet", "summary", "excerpt", "content", "text"]) {
    if (key in metadata) {
      delete metadata[key];
    }
  }

  return {
    title,
    url,
    snippet,
    metadata: Object.keys(metadata).length > 0 ? metadata : undefined,
  };
}

export function extractResultsFromStructuredContent(
  structuredContent: unknown
): NormalizedResult[] {
  if (Array.isArray(structuredContent)) {
    return structuredContent.map(normalizeEntry);
  }

  if (isRecord(structuredContent)) {
    const candidates = [
      structuredContent["results"],
      structuredContent["data"],
      structuredContent["items"],
      structuredContent["documents"],
      structuredContent["hits"],
      structuredContent["entries"],
    ];

    for (const candidate of candidates) {
      if (Array.isArray(candidate)) {
        return candidate.map(normalizeEntry);
      }
    }

    return [normalizeEntry(structuredContent)];
  }

  if (typeof structuredContent === "string") {
    return [{ text: structuredContent }];
  }

  return [];
}

export function extractResultsFromContent(content: unknown): NormalizedResult[] {
  if (!Array.isArray(content)) {
    return [];
  }

  const results: NormalizedResult[] = [];
  for (const item of content) {
    if (!isRecord(item) || typeof item["type"] !== "string") {
      continue;
    }

    if (item["type"] === "resource_link") {
      results.push({
        title: pickFirstString(item["name"]),
        url: pickFirstString(item["uri"]),
        snippet: pickFirstString(item["description"]),
      });
      continue;
    }

    if (item["type"] === "text") {
      const text = pickFirstString(item["text"]);
      if (text === undefined) {
        continue;
      }
      results.push(parseDocsTextBlock(text) ?? { text });
    }
  }

  return results.filter((result) =>
    result.title || result.url || result.snippet || result.text
  );
}

function getDocsMcpUrl(env: Record<string, string | undefined>): string {
  const url = env["PLANETSCALE_DOCS_MCP_URL"]?.trim();
  if (!url) {
    return DEFAULT_MCP_URL;
  }

  try {
    return new URL(url).toString();
  } catch {
    throw new Error("PLANETSCALE_DOCS_MCP_URL must be a valid URL");
  }
}

export const searchDocumentationGram = new Gram().tool({
  name: "search_documentation",
  description:
    "Search across the PlanetScale knowledge base to find relevant information, code examples, API references, and guides. Use this tool when you need to answer questions about PlanetScale, find specific documentation, understand how features work, or locate implementation details. The search returns contextual content with titles and direct links to the documentation pages.",
  annotations: {
    title: "Search PlanetScale documentation",
    readOnlyHint: true,
    destructiveHint: false,
    openWorldHint: false,
  },
  inputSchema: {
    query: z.string().describe("Search query for PlanetScale docs"),
  },
  async execute(ctx, input) {
    const env =
      Object.keys(ctx.env).length > 0
        ? (ctx.env as Record<string, string | undefined>)
        : process.env;

    let transport: StreamableHTTPClientTransport | undefined;

    try {
      const mcpUrl = getDocsMcpUrl(env);
      const client = new Client({ name: "planetscale-docs-wrapper", version: "1.0.0" });
      transport = new StreamableHTTPClientTransport(new URL(mcpUrl));

      await client.connect(transport);

      const result = await client.callTool({
        name: UPSTREAM_TOOL_NAME,
        arguments: { query: input.query },
      });

      const normalizedResults = result.structuredContent
        ? extractResultsFromStructuredContent(result.structuredContent)
        : extractResultsFromContent(result.content);

      return ctx.json({
        results: normalizedResults,
        total: normalizedResults.length,
        source: "planetscale-docs-mcp",
      });
    } catch (error) {
      // Fail loudly, following this codebase's `Error: ` text convention. The
      // old shape here was `{ results: [], total: 0, error }`, which reads
      // exactly like a search that legitimately matched nothing -- that is how
      // an upstream tool rename went unnoticed for months. `ctx.fail` is not
      // the alternative: it throws a Response, which the MCP adapter collapses
      // into a bare "-32603 Internal error" and drops the reason entirely.
      const message =
        error instanceof Error ? error.message : "An unexpected error occurred";
      return ctx.text(
        `Error: PlanetScale docs search is unavailable: ${message}`
      );
    } finally {
      if (transport) {
        await transport.close();
      }
    }
  },
});
